
- name: Text Edit - Use plain text mode for new TextEdit documents
  community.general.osx_defaults:
    domain: com.apple.TextEdit
    key: RichText
    type: int
    value: 0
    state: present

- name: Text Edit - Open files as UTF-8 in TextEdit
  community.general.osx_defaults:
    domain: com.apple.TextEdit
    key: PlainTextEncoding
    type: int
    value: 4
    state: present

- name: Text Edit - Save files as UTF-8 in TextEdit
  community.general.osx_defaults:
    domain: com.apple.TextEdit
    key: PlainTextEncodingForWrite
    type: int
    value: 4
    state: present
